title: Fathin Afif # your name (or website title) here
logo: "images/fathin-profile.png?raw=true" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Industrial Engineering graduate skilled in data-driven decision-making, proficient in SQL, Excel, Tableau, Power BI, Looker Studio, and Python. I have experience as a Project-Based Big Data Analytics Intern at Kimia Farma and as a Quality Control Analyst Intern at PT Bugak Palma Sejahtera.
  <br><br>
  Recently completed the Google Data Analytics Certificate, along with several other certificates related to data.
  <br><br>
  <a href="https://www.linkedin.com/in/fathinafiff/">View my LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here

colors:
  crimson: "#900C3F"
